#pragma once
#define FILE_DEVICE_VMOUSE 0x8001
#define IOCTL_VMOUSE_MOVE    CTL_CODE(FILE_DEVICE_VMOUSE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
typedef struct { LONG X; LONG Y; ULONG Flags; } VMOUSE_MOVE_DATA;
